bitbeckers/grants-round

- packages/round-manager/src/app/wagmi.ts
- packages/round-manager/src/features/api/contracts.ts
- packages/round-manager/src/features/api/utils.ts
- packages/round-manager/src/features/round/RoundDetailForm.tsx
* Added Mumbai contracts to app config
* Added Mumbai chain to app config
> chore(config): mumbai contracts for app

- packages/graph/config/mumbai.json
mumbai config for last deployment
> mumbai-config

- packages/graph/config/mumbai.json
- packages/graph/config/polygon-mumbai.json
- packages/graph/package.json
* merged config files for Graph deploy
> chore(config): merge config files mumbai

- packages/contracts/scripts/config/round.config.ts
- packages/contracts/scripts/config/votingStrategy.config.ts
- packages/contracts/scripts/votingStrategy/quadraticFundingRelay/castQFRelayViaRound.ts
Mumbai config
Success vote on round
> chore(vote): run vote on current round

- packages/contracts/scripts/config/round.config.ts
- packages/contracts/scripts/config/votingStrategy.config.ts
- packages/contracts/scripts/votingStrategy/quadraticFundingRelay/castQFRelayViaRound.ts
> chore(vote): active round params

- packages/contracts/scripts/round/createRound.ts
- packages/contracts/scripts/votingStrategy/quadraticFundingRelay/castQFRelayViaRound.ts
- packages/round-manager/src/features/api/utils.ts
WMATIC as round payment token option
> chore(token): set mumbai token as wmatic

- packages/contracts/scripts/config/payoutStrategy.config.ts
- packages/contracts/scripts/config/round.config.ts
- packages/contracts/scripts/config/votingStrategy.config.ts
> chore(round): set up current active round

- packages/contracts/scripts/votingStrategy/quadraticFundingRelay/castQFRelayViaRound.ts
> chore(vote): tweak voting data

- packages/contracts/scripts/config/round.config.ts
- packages/contracts/scripts/config/votingStrategy.config.ts
- packages/graph/config/mumbai.json
> chore(deploy): round addresses

- packages/contracts/contracts/payoutStrategy/IPayoutStrategy.sol
- packages/contracts/contracts/program/ProgramFactory.sol
- packages/contracts/contracts/votingStrategy/IVotingStrategy.sol
- packages/contracts/deployments/clone-deployments-localhost.json
- packages/contracts/deployments/clone-deployments-polygon-mumbai.json
- packages/contracts/deployments/deployments-localhost.json
- packages/contracts/deployments/deployments-polygon-mumbai.json
- packages/contracts/docs/contracts/round/RoundFactory.md
- packages/contracts/hardhat.config.ts
- packages/contracts/tasks/createRound.ts
fixed a bug in the createRound task that would break the task after the first round is created.  it now works as intended.
> createRound task fix

- packages/api/src/handlers/updateRoundMatchHandler.ts
- packages/api/src/handlers/updateRoundSummaryHandler.ts
- packages/api/src/votingStrategies/linearQuadraticFunding.ts
> feat(payouts): use graph instead of projectsMetaPtr to determine payouts

- packages/api/src/votingStrategies/linearQuadraticFunding.ts
- packages/round-manager/.env.sample
- packages/round-manager/src/context/round/FinalizeRoundContext.tsx
- packages/round-manager/src/features/api/round.ts
- packages/round-manager/src/features/api/utils.ts
- packages/round-manager/src/features/round/RoundDetailForm.tsx
- packages/round-manager/src/features/round/ViewFundingAdmin.tsx
- packages/round-manager/src/features/round/ViewRoundPage.tsx
> feat: display post url in funding admin overview

- packages/round-manager/src/features/round/ApplicationEligibilityForm.tsx
- packages/round-manager/src/features/round/RoundDetailForm.tsx
> feat: ui polish

- packages/round-manager/src/features/round/ApplicationEligibilityForm.tsx
- packages/round-manager/src/features/round/RoundApplicationForm.tsx
- packages/round-manager/src/features/round/RoundDetailForm.tsx
> fix: form validation

- packages/api/src/controllers/v1/routes.ts
- packages/api/src/database.ts
- packages/api/src/handlers/getProjectMatchDataByProjectIdsHandler.ts
> feat: add get project match info by project ids endpoint

- packages/api/index.ts
- packages/api/package.json
- packages/api/src/cron-jobs/index.ts
- packages/api/src/handlers/updateRoundMatchHandler.ts
- packages/api/src/lib/updateRoundMatch.ts
- packages/api/src/votingStrategies/linearQuadraticFunding.ts
- packages/api/yarn.lock
> feat: add cron job

- packages/api/src/votingStrategies/linearQuadraticFunding.ts
> fix: remove unnecessary log

- packages/api/src/cron-jobs/index.ts
> fix: update cron job interval and add timer to measure performance

- packages/api/src/cron-jobs/index.ts
- packages/api/src/votingStrategies/linearQuadraticFunding.ts
> fix: calculation of total contributions

- packages/round-manager/src/features/api/payoutStrategy/merklePayoutStrategy.ts
- packages/round-manager/src/features/api/round.ts
> fix: check if round is already set for payout on finalization

- packages/round-manager/src/features/api/utils.ts
> feat: add DragonHoard as a currency

- packages/api/src/controllers/v1/routes.ts
- packages/api/src/handlers/getMatchAmountPreviewHandler.ts
> feat: add preview match amount difference endpoint

- packages/api/src/utils.ts
> fix: add dragonhoard for calculations

- packages/api/src/cron-jobs/index.ts
> fix: set interval for cron job to 60

- packages/api/src/cron-jobs/index.ts
> fix: add better error handling

- packages/api/src/votingStrategies/linearQuadraticFunding.ts
> fix: fractional error

- packages/api/src/cron-jobs/index.ts
- packages/api/src/utils.ts
- packages/api/src/votingStrategies/linearQuadraticFunding.ts
> fix: multiple errors in cron job

- packages/api/src/handlers/getMatchAmountPreviewHandler.ts
> fix: no negative match differences

- packages/round-manager/src/app/wagmi.ts
- packages/round-manager/src/features/api/contracts.ts
- packages/round-manager/src/features/api/utils.ts
> feat: add polygon mainnet support

- packages/api/src/cron-jobs/index.ts
> feat: add polygon mainnet to active chains in batch job

- packages/api/src/votingStrategies/linearQuadraticFunding.ts
> fix: get active rounds query

- packages/api/src/lib/updateRoundMatch.ts
> fix: keep track of recent tip per user

- packages/api/src/lib/updateRoundMatch.ts
- packages/round-manager/src/features/api/utils.ts
> fix: only do a single payout per user
